#!/bin/bash

echo "🚀 PG Analytics v2 - Acesso Rápido"
echo "=================================="
echo ""
echo "📖 Documentação:"
echo "• README Principal: cat README.md | head -20"
echo "• Monitoramento: cat MONITORING.md | head -20"
echo ""
echo "🧪 Testes:"
echo "• Teste Completo: bash test_system_definitive.sh"
echo "• Teste Rápido: bash test_all.sh"
echo ""
echo "🌐 URLs Principais:"
echo "• Swagger Coletor C: http://localhost:8080/swagger"
echo "• Swagger Backend: http://localhost:8000/docs"
echo "• Grafana: http://localhost:3000"
echo "• Prometheus: http://localhost:9090"
echo ""
echo "🔧 Comandos Úteis:"
echo "• Status: docker-compose ps"
echo "• Logs: docker-compose logs -f [service]"
echo "• Restart: docker-compose restart [service]"
