groups:
- name: postgresql_opentelemetry
  rules:
  # Conexões
  - alert: PostgreSQLTooManyConnections
    expr: postgres_connections_total{state="active"} > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL tem muitas conexões ativas"
      description: "{{ $value }} conexões ativas detectadas"

  # Slow Queries
  - alert: PostgreSQLSlowQueries
    expr: increase(postgres_slow_queries_total[5m]) > 10
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Muitas slow queries detectadas"
      description: "{{ $value }} slow queries nos últimos 5 minutos"

  # Cache Hit Ratio
  - alert: PostgreSQLLowCacheHitRatio
    expr: postgres_cache_hit_ratio < 0.95
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Cache hit ratio baixo"
      description: "Cache hit ratio: {{ $value | humanizePercentage }}"

  # Deadlocks
  - alert: PostgreSQLDeadlocks
    expr: increase(postgres_deadlocks_total[10m]) > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Deadlocks detectados"
      description: "{{ $value }} deadlocks nos últimos 10 minutos"

  # Replication Lag
  - alert: PostgreSQLReplicationLag
    expr: postgres_replication_lag_bytes > 50000000  # 50MB
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Replication lag alto"
      description: "Lag de replicação: {{ $value | humanizeBytes }}"

  # Coletor inativo
  - alert: OpenTelemetryCollectorDown
    expr: up{job="otel-collector"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Coletor OpenTelemetry inativo"
      description: "O coletor OpenTelemetry não está respondendo"
