global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Cliente C BYPASS (direto)
  - job_name: 'pganalytics-c-bypass'
    static_configs:
      - targets: ['c-bypass-collector:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
